### ISSUE TITLE
Example unittest 

### ISSUE THREAD

**Issue by sir-wiggles** [rayrapetyan/flask-spyne#4]
Would it be possible to give a sample unittest. I've been trying to figure it out using the example for the basic sypne  library but can't figure out how to get it to work with flask.

Great work by the way. A real life saver.

**Comment by rayrapetyan** [comment]
Hi, thanks for your interest. You can find basic server\client examples in "examples" folder (https://github.com/rayrapetyan/flask-spyne/tree/master/examples).

**Comment by sir-wiggles** [comment]
I see the example and can get them to work no problem.  But what I'm trying to do is write some unittests without starting a server for every test.  

So I'm trying to figure out how to write unittests that would be similar to the flask style of unittesting
```python
test_client = app.test_client()
test_client.get("/foo")
```
This [SO question](https://stackoverflow.com/questions/19383937/testing-spyne-application) is what I'm looking for but with your library

Hope that makes sense.

**Comment by rayrapetyan** [comment]
Oh, so you want to run tests without running WSGI server... Not sure it's possible with a current implementation based on WsgiApplication

**Comment by sir-wiggles** [comment]
Ah ok I see thanks for the quick replies

**Comment by sir-wiggles** [comment]
Actually it looks like it can be done... I think.  At least with the solution give in the SO question above.  The problem is there's a logging line in `flask_spyne.py:58` that's trying to format the `in_document` which is `None` (not sure if it's supposed to be) but if I comment this line out then I get the expected result without having to have the wsgi server up.

```python
from spyne.application import Application
from spyne.server.null import NullServer
from spyne.protocol.soap import Soap11

from server import SomeSoapService


app = Application(
    [SomeSoapService],
    'foo.bar',
    in_protocol=Soap11(validator='lxml'),
    out_protocol=Soap11(pretty_print=True),
)
null = NullServer(app)

r = null.service.echo(str='foo bar', cnt=3)
print(list(r)) # output: ['foo bar', 'foo bar', 'foo bar']
```
Maybe this will help someone else trying to figure this out.
