### ISSUE TITLE
max_content_length can't be set

### ISSUE THREAD

**Issue by kpoman** [rayrapetyan/flask-spyne#8]
Hello,
I am building a flask app with a backend spyne webservice and getting "Request too long" error. I checked the code and it seems one cannot set it on the Spyne initialization nor does it propagate max_content_length from it's parent wsgi app (here, the flask app itself), as can be seen on SpyneController.register_service method ! This is annoying as the default limit is set to 2MB.
Is there any elegant way of setting this limit other than monkey-patching the initialization (example: wsgi_app = WsgiApplication(spyne_app, max_content_length=10 * 1024 * 1024) ) ?
Thank you !

**Comment by rayrapetyan** [comment]
Try this:
...
spyne = Spyne(app)
spyne.controller.services['/soap/someservice'].max_content_length = 10 * 1024 * 1024
...
